spring:
  application:
    name: Busuu

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        cache:
          use_second_level_cache: true
          use_query_cache: true

  messages:
    basename: i18n/messagesR
    encoding: UTF-8
    default-locale: en

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

  servlet:
    multipart:
      max-file-size: ${MULTIPART_MAX_FILE_SIZE}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
            redirect-uri: ${OAUTH_GOOGLE_REDIRECT_URI}
            scope: [email, profile]
            provider: google
          facebook:
            client-id: ${OAUTH_FACEBOOK_CLIENT_ID}
            client-secret: ${OAUTH_FACEBOOK_CLIENT_SECRET}
            redirect-uri: ${OAUTH_FACEBOOK_REDIRECT_URI}
            scope: [email, public_profile]
            provider: facebook
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          facebook:
            authorization-uri: https://www.facebook.com/v21.0/dialog/oauth
            token-uri: https://graph.facebook.com/v21.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture
            user-name-attribute: id

  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false

server:
  servlet:
    context-path: ${CONTEXT_PATH}

jwt:
  expiration: ${JWT_EXPIRATION}
  expiration-refresh-token: ${JWT_EXPIRATION_REFRESH}
  secretKey: ${JWT_SECRET}

logging:
  level:
    org:
      hibernate:
        cache:
          spi: TRACE
        engine:
          internal:
            StatisticalLoggingSessionEventListener: DEBUG
      springframework:
        security: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        include: "health, info"

cache:
  redis:
    expiration: ${CACHE_EXPIRATION}
    cluster: ${CACHE_CLUSTER}
    server: ${CACHE_SERVER}
    db: ${CACHE_DB}
    connection-pool-size: ${CACHE_CONNECTION_POOL_SIZE}
    connection-minimum-idle-size: ${CACHE_CONNECTION_MIN_IDLE_SIZE}
    subscription-connection-pool-size: ${CACHE_SUBSCRIPTION_POOL_SIZE}
    ttl: ${CACHE_TTL}

services:
  openai:
    endpoint: ${OPENAI_ENDPOINT}
    model: ${OPENAI_MODEL}
    api-key: ${OPENAI_API_KEY}
