spring:
  application:
    name: Busuu
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/busuu-learn-language?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_ROOT_PASSWORD:Busuu@230523}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        cache:
          use_second_level_cache: true
          use_query_cache: true

  messages:
    basename: i18n/messagesR
    encoding: UTF-8
    default-locale: en
  mail:
    host: smtp.gmail.com
    port: 587
    username: busuu.service@gmail.com
    password: ccdpsjepfylqftts
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#  flyway:
#    enabled: true
#    locations: classpath:/db/migration,classpath:/dev/db/migration
#    baseline-on-migrate: true
#    baseline-version: 0
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 395250688466-fun0nunkb1audoiv8leiiuediv3365ko.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:3000/auth/google/callback"
            scope:
              - email
              - profile
            provider: google

          facebook:
            client-id: 1466181787896061
            client-secret: 331779654921601ddbc793c2807a5069
            redirect-uri: "http://localhost:3000/auth/facebook/callback"
            scope:
              - email
              - public_profile
            provider: facebook

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

          facebook:
            authorization-uri: https://www.facebook.com/v21.0/dialog/oauth
            token-uri: https://graph.facebook.com/v21.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture
            user-name-attribute: id
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
server:
  servlet:
    context-path: ${CONTEXT_PATH:/api/v1}

jwt:
  expiration: 2592000 #30 days
  expiration-refresh-token: 5184000 #60 days
  secretKey: jtc6zcRYQr5lZj4UCIwkIbLjpP/AhDbSiZhUHa5VoGw=

logging:
  level:
    org:
      hibernate:
        cache:
          spi: TRACE
        engine:
          internal:
            StatisticalLoggingSessionEventListener: DEBUG
      springframework:
        security: DEBUG

# Swagger-UI custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

# Health check
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        #include: "health"
        include: "health, info"

cache:
  redis:
    expiration: 3600
    cluster: false
    server: redis://127.0.0.1:6379
    db: 0
    connection-pool-size: 8
    connection-minimum-idle-size: 2
    subscription-connection-pool-size: 8
    ttl: 5

services:
  openai:
    endpoint: ${ENDPOINT:https://api.openai.com/v1}
    model: ${MODEL:gpt-4.1-nano}
    api-key: ${API-KEY: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}

