spring:
  application:
    name: Busuu
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/busuu-learn-language?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        cache:
          use_second_level_cache: true
          use_query_cache: true

  messages:
    basename: i18n/messagesR
    encoding: UTF-8
    default-locale: en
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}
#  flyway:
#    enabled: true
#    locations: classpath:/db/migration,classpath:/dev/db/migration
#    baseline-on-migrate: true
#    baseline-version: 0
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - email
              - profile
            provider: google

          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            redirect-uri: ${FACEBOOK_REDIRECT_URI}
            scope:
              - email
              - public_profile
            provider: facebook

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

          facebook:
            authorization-uri: https://www.facebook.com/v21.0/dialog/oauth
            token-uri: https://graph.facebook.com/v21.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture
            user-name-attribute: id
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
server:
  servlet:
    context-path: ${CONTEXT_PATH:/api/v1}

jwt:
  expiration: ${JWT_EXPIRATION}
  expiration-refresh-token: ${JWT_EXPIRATION_REFRESH_TOKEN}
  secretKey: ${JWT_SECRET_KEY}

logging:
  level:
    org:
      hibernate:
        cache:
          spi: TRACE
        engine:
          internal:
            StatisticalLoggingSessionEventListener: DEBUG
      springframework:
        security: DEBUG

# Swagger-UI custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

# Health check
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        #include: "health"
        include: "health, info"

cache:
  redis:
    expiration: ${REDIS_EXPIRATION}
    cluster: ${REDIS_CLUSTER}
    server: ${REDIS_SERVER}
    db: ${REDIS_DB}
    connection-pool-size: ${CONNECTION_POOL_SIZE:8}
    connection-minimum-idle-size: ${CONNECTION_MINIMUM_IDE_SIZE:2}
    subscription-connection-pool-size: ${SUBSCRIPTION_CONNECTION_POOL_SIZE:8}
    ttl: 5

services:
  openai:
    endpoint: ${OPENAI_ENDPOINT}
    model: ${OPENAI_MODEL}
    api-key: ${OPENAI_API_KEY}

